In [1]:
import numpy as np

In [5]:
l = [[[1,2,3],
    [4,5,6],
    [7,8,9]],
     
    [[10,11,12],
    [13,14,15],
    [16,17,18]]]

for d in enumerate(l):
    print(d)
    print()
    for r in enumerate(l[d[0]]):
        print(r)
        for c in enumerate(l[d[0]][r[0]]):
            print(l[d[0]][r[0]])
            l[d[0]][r[0]][c[0]] += 5


l

(0, [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

(0, [1, 2, 3])
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
(1, [4, 5, 6])
[4, 5, 6]
[4, 5, 6]
[4, 5, 6]
(2, [7, 8, 9])
[7, 8, 9]
[7, 8, 9]
[7, 8, 9]
(1, [[10, 11, 12], [13, 14, 15], [16, 17, 18]])

(0, [10, 11, 12])
[10, 11, 12]
[10, 11, 12]
[10, 11, 12]
(1, [13, 14, 15])
[13, 14, 15]
[13, 14, 15]
[13, 14, 15]
(2, [16, 17, 18])
[16, 17, 18]
[16, 17, 18]
[16, 17, 18]


In [16]:
arr4 = np.arange(64).reshape(2,2,4,4)
arr4

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]],


       [[[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]])

In [17]:
#streamlite
#kiwy
#deep fake
#p360.hockey
#agha adnan
#hnowledge base worker

In [18]:
%%time 

[i+5 for i in range(1,1000000)]

Wall time: 361 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


In [22]:
%%time
arr1 = np.arange(1,1000000)+5
print(arr1)

[      6       7       8 ... 1000002 1000003 1000004]
Wall time: 22 ms


In [25]:
print(8.97/126*100)

7.1190476190476195


In [6]:
%history

%history
import numpy as np
l = [[[1,2,3],
    [4,5,6],
    [7,8,9]],
     
    [[10,11,12],
    [13,14,15],
    [16,17,18]]]

for d in enumerate(l):
    print(d)
    print()
    for r in enumerate(l[d[0]]):
        print(r)
        for c in enumerate(l[d[0]][r[0]]):
            print(l[d[0]][r[0]])
#             l[d[0]][r[0]][c[0]] += 5

#             print(c)
#         for c in enumerate(l[[0]]):
#             print(c)
# l
%history
l = [[[1,2,3],
    [4,5,6],
    [7,8,9]],
     
    [[10,11,12],
    [13,14,15],
    [16,17,18]]]

for d in enumerate(l):
    print(d)
    print()
    for r in enumerate(l[d[0]]):
        print(r)
        for c in enumerate(l[d[0]][r[0]]):
            print(l[d[0]][r[0]])
%history


In [7]:
print("Hello")

Hello


In [9]:
%history

%history
import numpy as np
l = [[[1,2,3],
    [4,5,6],
    [7,8,9]],
     
    [[10,11,12],
    [13,14,15],
    [16,17,18]]]

for d in enumerate(l):
    print(d)
    print()
    for r in enumerate(l[d[0]]):
        print(r)
        for c in enumerate(l[d[0]][r[0]]):
            print(l[d[0]][r[0]])
#             l[d[0]][r[0]][c[0]] += 5

#             print(c)
#         for c in enumerate(l[[0]]):
#             print(c)
# l
%history
l = [[[1,2,3],
    [4,5,6],
    [7,8,9]],
     
    [[10,11,12],
    [13,14,15],
    [16,17,18]]]

for d in enumerate(l):
    print(d)
    print()
    for r in enumerate(l[d[0]]):
        print(r)
        for c in enumerate(l[d[0]][r[0]]):
            print(l[d[0]][r[0]])
%history
print("Hello")
%history
%history


In [23]:
%%time
l = list(range(3000))

Wall time: 1.06 s


In [24]:
%%time
[x+5 for x in range(300)][:10]


Wall time: 0 ns


[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [26]:
l1 = [1,2,3,4,5,6,7,8,9]
for i,d in enumerate(l1):
    l1[i] = l1[i] + 5
    
l1

[6, 7, 8, 9, 10, 11, 12, 13, 14]

In [28]:
l2 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
for ri,rd in enumerate(l2):
    for ci,cd in enumerate(rd):
        l2[ri][ci] = l2[ri][ci] + 4
        
l2

[[5, 6, 7], [8, 9, 10], [11, 12, 13]]

In [30]:
l3 = [[[1,2,3],
       [4,5,6],
       [7,8,9]],
     
     
     [[1,2,3],
       [4,5,6],
       [7,8,9]]]

In [41]:
for di,dd in enumerate(l3):
    for ri,rd in enumerate(dd):
        for ci,cd in enumerate(rd):
            l3[di][ri][ci] +=7
l3

[[[22, 23, 24], [25, 26, 27], [28, 29, 30]],
 [[22, 23, 24], [25, 26, 27], [28, 29, 30]]]

In [46]:
arr1 = [1,2,3]
print(sum(arr1))
print(np.sum(arr1))

6
6


In [53]:
arr2 = np.arange(1,13).reshape((2,-1))
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
l1 = np.arange(1,28).reshape(3,3,3)
l1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [61]:
l1[[2,1,0]][:,1:2,1]

array([[23],
       [14],
       [ 5]])

In [62]:
l1[1][2][0]

16

In [67]:
l2 = np.array(["a","b","c"])
l2
l2[[True,False,True]]

array(['a', 'c'], dtype='<U1')

In [72]:
l1 = np.arange(1,28).reshape(3,3,3)
[l1 % 3 == 0]

[array([[[False, False,  True],
         [False, False,  True],
         [False, False,  True]],
 
        [[False, False,  True],
         [False, False,  True],
         [False, False,  True]],
 
        [[False, False,  True],
         [False, False,  True],
         [False, False,  True]]])]

In [73]:
l1[l1%3== 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [77]:
l1 = np.arange(1,28).reshape(3,3,3)
l1[(l1%3==0) & (l1%9==0)]

array([ 9, 18, 27])

In [88]:
l3 = np.random.randn(3,3,3)
l3.itemsize

8

In [89]:
# l3+2
# l3-2
# l3*2
# l3/2
# l3**2
# l3**0.5
# l3%3

In [90]:
# deep copy
l = [1,2,3]
a = np.array(l)
b = np.array(a)

In [94]:
type(l)
type(a)
type(b)

numpy.ndarray

In [98]:
a is l
b is a
a is b

False

In [100]:
# shallow copy         pass by reference   
c = [1,2,3]
d = c

c is d

True

In [109]:
l = [1,2,3]
print(type(l))

a = np.asarray(l)
b = np.asarray(a)
c = np.asarray(b, dtype=np.float64)
print(a is l)
print(b is a)
print(c is b)

<class 'list'>
False
True
False


In [115]:
a = np.array([1,2], np.int32)
a.itemsize

4

In [117]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])

In [122]:
def A(x):
    return x+5

In [125]:
def B(x):
    return x+6
    
def C(x):
    return x+7

In [126]:
C(B(A(1)))

19

In [127]:
A(B(C(2)))

20

In [137]:
a = np.arange(1,28).reshape(3,3,3)
b = np.reshape(a,(27,1))

In [136]:
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [143]:
a = np.arange(27)
a.ndim

a.shape = (3,9)
a.ndim

2

In [146]:
a = np.zeros((3,9))

In [149]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [151]:
np.zeros((a.shape[0],a.shape[1]))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [156]:
np.zeros(a.shape)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [157]:
np.zeros_like(a)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [158]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [161]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [162]:
np.ones_like(a)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [163]:
c = np.ones_like(a) * 5
c

array([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [165]:
c.transpose()

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [168]:
c.T

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [169]:
b = np.full((3,3),6)
b

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [174]:
b = np.full(a.shape,7)
b

array([[7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [176]:
c = np.full_like(b,8)
c

array([[8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [183]:
d = np.full_like(c, dtype=c.dtype,fill_value=4.9)
d

array([[4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [186]:
np.full_like(a, dtype=np.float64, fill_value=3.5)

array([[3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5]])

In [209]:
e = np.empty((5,2))

In [210]:
np.empty_like(e)

array([[           nan, 0.0000000e+000],
       [3.8869275e-316, 2.0236929e-320],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

In [213]:
f = np.full_like(a,np.nan)
f

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [214]:
f = np.full_like(a,1) * np.nan
f

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [220]:
np.full(a.shape,np.nan)

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [228]:
g = np.eye(6)
g

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [240]:
np.eye(6)     #dusri value dy sakte hain

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [238]:
h = np.identity(6)      #dusri value nhi dy sakte
h

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Data types

In [241]:
a = np.array([1,2,3], dtype=int)
a.dtype

dtype('int32')

In [243]:
a = np.array([1,2,3], dtype="int")
a.dtype

dtype('int32')

In [247]:
a = np.array([1,2,3], dtype=np.int64)
a.dtype

dtype('int64')

In [256]:
a = np.array([1,2,3], dtype='i8')
a.dtype

dtype('int64')

In [259]:
b = np.array([1,2,3], dtype=a.dtype)
b.dtype

dtype('int64')

In [262]:
b = b.astype(np.int32)
b.dtype

dtype('int32')

# boolean operation  and boolean indexing

In [289]:
a = np.arange(27).reshape(3,3,3)
# [(a%3==0)] 
a%3==0

array([[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]]])

In [268]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [270]:
a[(a%3==0) & (a%5==0)]

array([ 0, 15])

In [272]:
a[(a%3==0) | (a%5==0)]

array([ 0,  3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25])

In [293]:
print(a)
[~a%3==0]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[False, False,  True],
         [False, False,  True],
         [False, False,  True]],
 
        [[False, False,  True],
         [False, False,  True],
         [False, False,  True]],
 
        [[False, False,  True],
         [False, False,  True],
         [False, False,  True]]])]

In [290]:
[~(a%3==0)]

[array([[[False,  True,  True],
         [False,  True,  True],
         [False,  True,  True]],
 
        [[False,  True,  True],
         [False,  True,  True],
         [False,  True,  True]],
 
        [[False,  True,  True],
         [False,  True,  True],
         [False,  True,  True]]])]

In [291]:
a[a%3!=0]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [294]:
a = np.arange(1,7).reshape(2,3,1)
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

# fancy slicing

In [2]:
b = np.arange(10,3*3*3+10).reshape(3,3,3)
b

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [301]:
b[1,1,1]

23

In [303]:
b[[2,0,1]]

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [306]:
print(b)
b[[2,0,1],[2,0,1],[2,0,1]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([36, 10, 23])

In [3]:
b

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [88]:
# b[1,1,1]
# b[[1,0,2]]
# b[[2,0,1],[2,0,1],[2,0,1]]
# b[[0,1,2],[0,1,2]]
# b[:,[1,0,2]]
# b[[1,2,0]][:,[-1,0]]
# b[[1,2,0],:,::-1]
# b[::-1]
# b[:,::-1,:]
# b[[1],[1],[1]]
# b[1:,1:,1:]
# b[[1:][1:][1:]]  wrong way
# b[1:][1:][1:]      no element return 
# b[:2,:2,:2]
# b[:,:,:]
# b[::-1,::-1,::-1]
# b[[2,1,0]][:,[1,0]]
# b[[2,1,0]][[1,0],[1,0]]
# b[[2,1,0]][[1,0],[1,0],[1,0]]
# b[[2,0]],[[2,0]],[[2,0]]
# b[[2,0],[2,0],[2,0]]

array([[22, 23, 24],
       [28, 29, 30]])

In [83]:
names = np.array(["Qasim","Ahmed","Ali","Zubair","Qasim","Junaid"])

data = np.random.rand(6,4)
print(names,data,sep='\n\n\n')

['Qasim' 'Ahmed' 'Ali' 'Zubair' 'Qasim' 'Junaid']


[[0.98057481 0.29939174 0.70577627 0.68712819]
 [0.45387217 0.2622199  0.4683989  0.88695469]
 [0.13364155 0.09817189 0.23588285 0.4094435 ]
 [0.75593838 0.28483634 0.48910419 0.94563272]
 [0.37139375 0.02424014 0.00788465 0.42417023]
 [0.13681958 0.78457483 0.1671479  0.22740382]]


In [91]:
names == "Qasim"

array([ True, False, False, False,  True, False])

In [93]:
names[names=="Qasim"]

array(['Qasim', 'Qasim'], dtype='<U6')

In [97]:
data[[True,False,False,False,True,False]]

array([[0.98057481, 0.29939174, 0.70577627, 0.68712819],
       [0.37139375, 0.02424014, 0.00788465, 0.42417023]])

In [99]:
names = np.array(["Qasim","Ahmed","Ali","Zubair","Qasim","Junaid"])

data = np.random.rand(6,4)
print(names,data,sep='\n\n\n')
data[names=="Qasim"]

['Qasim' 'Ahmed' 'Ali' 'Zubair' 'Qasim' 'Junaid']


[[0.20974995 0.29744348 0.93660446 0.78752314]
 [0.68912096 0.23832366 0.66611342 0.72339351]
 [0.23546339 0.16175783 0.55820776 0.54596699]
 [0.02588213 0.89877793 0.97231632 0.87432927]
 [0.32221901 0.36844129 0.34032555 0.7070275 ]
 [0.61035815 0.61320468 0.84561229 0.42683866]]


array([[0.20974995, 0.29744348, 0.93660446, 0.78752314],
       [0.32221901, 0.36844129, 0.34032555, 0.7070275 ]])

In [101]:
names = np.array(["Qasim","Ahmed","Ali","Zubair","Qasim","Junaid"])

data = np.random.rand(6,4)
print(names,data,sep='\n\n\n')

data[(names=="Qasim") | (names=="Ali")]

['Qasim' 'Ahmed' 'Ali' 'Zubair' 'Qasim' 'Junaid']


[[0.63719563 0.66883262 0.23875789 0.39521756]
 [0.28746446 0.3876903  0.56922069 0.97032361]
 [0.98805037 0.77520895 0.60941619 0.23242279]
 [0.71396899 0.86624211 0.2650495  0.44148343]
 [0.80965901 0.75693795 0.5532851  0.97454249]
 [0.08123127 0.03986882 0.66036299 0.48537376]]


array([[0.63719563, 0.66883262, 0.23875789, 0.39521756],
       [0.98805037, 0.77520895, 0.60941619, 0.23242279],
       [0.80965901, 0.75693795, 0.5532851 , 0.97454249]])

In [113]:
data[(names != "Qasim") & (names != "Zubair") & (names!= "Ali")]

array([[0.28746446, 0.3876903 , 0.56922069, 0.97032361],
       [0.08123127, 0.03986882, 0.66036299, 0.48537376]])

In [114]:
data((names != "Qasim") | (names != "Zubair"))

TypeError: 'numpy.ndarray' object is not callable

In [115]:
data[(names != "Qasim") | (names != "Zubair")]

array([[0.63719563, 0.66883262, 0.23875789, 0.39521756],
       [0.28746446, 0.3876903 , 0.56922069, 0.97032361],
       [0.98805037, 0.77520895, 0.60941619, 0.23242279],
       [0.71396899, 0.86624211, 0.2650495 , 0.44148343],
       [0.80965901, 0.75693795, 0.5532851 , 0.97454249],
       [0.08123127, 0.03986882, 0.66036299, 0.48537376]])

In [120]:
data[(names=="Qasim") | (names=="Ali")][:,[0,-1]]       #fancy indexing in coloum

array([[0.63719563, 0.39521756],
       [0.98805037, 0.23242279],
       [0.80965901, 0.97454249]])

In [ ]:
data[(names=="Qasim") | (names=="Ali")][:,:-1]        #fancy slicng is not available      slicng is normal avalable

In [130]:
l = [1,2,3,4,5]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [131]:
l = [1,2,3,4,5]
l[:3]
l[:3] = [7,7,7]
l

[7, 7, 7, 4, 5]

In [132]:
l1 = np.array([1,2,3,4,5])
l1[:3] = 6
l1

array([6, 6, 6, 4, 5])

In [135]:
l2 = np.arange(8*4).reshape(8,4)
print(l2)

for i in range(8):
    l2[i] = i
    
print(l2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [139]:
l3 = np.arange(32).reshape(8,4)
for i in range(len(l3)):
    l3[i] = i
print(l3)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [143]:
for i in range(l3.shape[0]):
    l3[i] = i
print(l3)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [144]:
for i in range(l3.shape[0]):
    l3[i] = i
    print(l3)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [147]:
l4 = l3.copy()
l4 is l3

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [150]:
for i,_ in enumerate(l4):
    l4[i] = i
print(l4)
    

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


# Transposing Arrays and Swapping Axes

In [152]:
a = np.arange(4*3).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [156]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [158]:
a.T.T.T.T

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [160]:
a.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [167]:
a = np.array([[1,2],
             [3,4]])

b = a+2

print(a,b, sep='\n\n', end='-')

a*b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]-

array([[ 3,  8],
       [15, 24]])

In [170]:
a = np.array([[1,2],
             [3,4]])

b = a+2

print(a,b, sep='\n\n', end='-')

a@b
np.dot(a,b)
a.dot(b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]-

array([[13, 16],
       [29, 36]])

In [171]:
a.dot(a.T)             #  [[1,3],                [[1,3],
                            [2,4]]              [2,4]]

array([[ 5, 11],
       [11, 25]])

In [174]:
c = np.arange(3*3*3).reshape(3,3,3)
print(c)
c.T            #   har pic ya depth    ka same coloum utha kr aik pic banana

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [176]:
d = np.arange(64).reshape(2,4,8)
d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [177]:
d.T

array([[[ 0, 32],
        [ 8, 40],
        [16, 48],
        [24, 56]],

       [[ 1, 33],
        [ 9, 41],
        [17, 49],
        [25, 57]],

       [[ 2, 34],
        [10, 42],
        [18, 50],
        [26, 58]],

       [[ 3, 35],
        [11, 43],
        [19, 51],
        [27, 59]],

       [[ 4, 36],
        [12, 44],
        [20, 52],
        [28, 60]],

       [[ 5, 37],
        [13, 45],
        [21, 53],
        [29, 61]],

       [[ 6, 38],
        [14, 46],
        [22, 54],
        [30, 62]],

       [[ 7, 39],
        [15, 47],
        [23, 55],
        [31, 63]]])

In [181]:
e = np.arange(5*6*7).reshape(5,6,7)
e

array([[[  0,   1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41]],

       [[ 42,  43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76],
        [ 77,  78,  79,  80,  81,  82,  83]],

       [[ 84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97],
        [ 98,  99, 100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125]],

       [[126, 127, 128, 129, 130, 131, 132],
        [133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146],
        [147, 148, 149, 150, 151, 152, 153],
    

In [182]:
e.T

array([[[  0,  42,  84, 126, 168],
        [  7,  49,  91, 133, 175],
        [ 14,  56,  98, 140, 182],
        [ 21,  63, 105, 147, 189],
        [ 28,  70, 112, 154, 196],
        [ 35,  77, 119, 161, 203]],

       [[  1,  43,  85, 127, 169],
        [  8,  50,  92, 134, 176],
        [ 15,  57,  99, 141, 183],
        [ 22,  64, 106, 148, 190],
        [ 29,  71, 113, 155, 197],
        [ 36,  78, 120, 162, 204]],

       [[  2,  44,  86, 128, 170],
        [  9,  51,  93, 135, 177],
        [ 16,  58, 100, 142, 184],
        [ 23,  65, 107, 149, 191],
        [ 30,  72, 114, 156, 198],
        [ 37,  79, 121, 163, 205]],

       [[  3,  45,  87, 129, 171],
        [ 10,  52,  94, 136, 178],
        [ 17,  59, 101, 143, 185],
        [ 24,  66, 108, 150, 192],
        [ 31,  73, 115, 157, 199],
        [ 38,  80, 122, 164, 206]],

       [[  4,  46,  88, 130, 172],
        [ 11,  53,  95, 137, 179],
        [ 18,  60, 102, 144, 186],
        [ 25,  67, 109, 151, 193],
        [ 32

In [183]:
f = np.arange(1,5*6*7).reshape(5,6,7)      # keep parctice for particular starting or particular ending point
f

ValueError: cannot reshape array of size 209 into shape (4,6,7)

In [193]:
g = c[:]
print(g)
print()
print(g.transpose(2,1,0))
print()
print(g.transpose(2,0,1))
print()
print(g.transpose(1,2,0))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]

[[[ 0  3  6]
  [ 9 12 15]
  [18 21 24]]

 [[ 1  4  7]
  [10 13 16]
  [19 22 25]]

 [[ 2  5  8]
  [11 14 17]
  [20 23 26]]]

[[[ 0  9 18]
  [ 1 10 19]
  [ 2 11 20]]

 [[ 3 12 21]
  [ 4 13 22]
  [ 5 14 23]]

 [[ 6 15 24]
  [ 7 16 25]
  [ 8 17 26]]]
